spring:
  application:
    name: discodeit
    profiles:
      active: dev   # dev, prod 선택 가능
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    #        default_batch_fetch_size: 100
    open-in-view: false


# log
logging:
  level:
    root: info
    # Hibernate SQL
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace
    # Spring Web
    org.springframework.web: trace
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage
